"""quote_additions

Revision ID: b92b3fcba5e8
Revises: a94a6f9f0703
Create Date: 2025-02-23 21:14:49.892235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92b3fcba5e8'
down_revision: Union[str, None] = 'a94a6f9f0703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('text', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('author', sa.String(), nullable=True))
    op.create_index(op.f('ix_quotes_author'), 'quotes', ['author'], unique=False)
    op.create_index(op.f('ix_quotes_text'), 'quotes', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_text'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_author'), table_name='quotes')
    op.drop_column('quotes', 'author')
    op.drop_column('quotes', 'text')
    # ### end Alembic commands ###
