"""added_fields

Revision ID: 12ab6e11118b
Revises: 90d9d58e3ddf
Create Date: 2025-02-24 21:23:29.628023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ab6e11118b'
down_revision: Union[str, None] = '90d9d58e3ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'api_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('books', sa.Column('api_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_api_id'), 'books', ['api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_api_id'), table_name='books')
    op.drop_column('books', 'api_id')
    op.alter_column('authors', 'api_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
