"""author_books_table_fixup

Revision ID: 39a59824670a
Revises: 12ab6e11118b
Create Date: 2025-02-24 21:35:31.152166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a59824670a'
down_revision: Union[str, None] = '12ab6e11118b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_books_author_id', table_name='authors_books')
    op.create_index(op.f('ix_authors_books_author_id'), 'authors_books', ['author_id'], unique=False)
    op.drop_index('ix_authors_books_book_id', table_name='authors_books')
    op.create_index(op.f('ix_authors_books_book_id'), 'authors_books', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_books_book_id'), table_name='authors_books')
    op.create_index('ix_authors_books_book_id', 'authors_books', ['book_id'], unique=True)
    op.drop_index(op.f('ix_authors_books_author_id'), table_name='authors_books')
    op.create_index('ix_authors_books_author_id', 'authors_books', ['author_id'], unique=True)
    # ### end Alembic commands ###
